// Code generated by mus-gen. DO NOT EDIT.

package pkg

import (
	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/varint"
)

var IntMUS = intMUS{}

type intMUS struct{}

func (s intMUS) Marshal(v Int, bs []byte) (n int) {
	return varint.Int.Marshal(int(v), bs)
}

func (s intMUS) Unmarshal(bs []byte) (v Int, n int, err error) {
	tmp, n, err := varint.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	v = Int(tmp)
	return
}

func (s intMUS) Size(v Int) (size int) {
	return varint.Int.Size(int(v))
}

func (s intMUS) Skip(bs []byte) (n int, err error) {
	return varint.Int.Skip(bs)
}

var FooMUS = fooMUS{}

type fooMUS struct{}

func (s fooMUS) Marshal(v Foo[Int], bs []byte) (n int) {
	n = ord.String.Marshal(v.S, bs)
	return n + IntMUS.Marshal(v.T, bs[n:])
}

func (s fooMUS) Unmarshal(bs []byte) (v Foo[Int], n int, err error) {
	v.S, n, err = ord.String.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	v.T, n1, err = IntMUS.Unmarshal(bs[n:])
	n += n1
	return
}

func (s fooMUS) Size(v Foo[Int]) (size int) {
	size = ord.String.Size(v.S)
	return size + IntMUS.Size(v.T)
}

func (s fooMUS) Skip(bs []byte) (n int, err error) {
	n, err = ord.String.Skip(bs)
	if err != nil {
		return
	}
	var n1 int
	n1, err = IntMUS.Skip(bs[n:])
	n += n1
	return
}
