// Code generated by AI agent with mus-skill. DO NOT EDIT.

package main

import (
	com "github.com/mus-format/common-go"
	stropts "github.com/mus-format/mus-go/options/string"
	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/raw"
)

var (
	CustomFooMUS = customFooMUS{}

	string4DZReIiCkP2x0bSFivrFsAΞΞ = ord.NewValidStringSer(
		stropts.WithLenValidator(com.ValidatorFn[int](ValidateLength)),
	)
)

type customFooMUS struct{}

func (s customFooMUS) Marshal(v Foo, bs []byte) (n int) {
	n = raw.Int.Marshal(v.Num, bs)
	return n + string4DZReIiCkP2x0bSFivrFsAΞΞ.Marshal(v.Str, bs[n:])
}

func (s customFooMUS) Unmarshal(bs []byte) (v Foo, n int, err error) {
	v.Num, n, err = raw.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	v.Str, n1, err = string4DZReIiCkP2x0bSFivrFsAΞΞ.Unmarshal(bs[n:])
	n += n1
	return
}

func (s customFooMUS) Size(v Foo) (size int) {
	return raw.Int.Size(v.Num) + string4DZReIiCkP2x0bSFivrFsAΞΞ.Size(v.Str)
}

func (s customFooMUS) Skip(bs []byte) (n int, err error) {
	n, err = raw.Int.Skip(bs)
	if err != nil {
		return
	}
	var n1 int
	n1, err = string4DZReIiCkP2x0bSFivrFsAΞΞ.Skip(bs[n:])
	n += n1
	return
}
