// Code generated by AI agent with mus-skill. DO NOT EDIT.

package main

import (
	"errors"
	"testing"

	"github.com/mus-format/mus-go/test"
)

func TestCustomFooMUS(t *testing.T) {
	var (
		ser   = CustomFooMUS
		cases = []Foo{
			{Num: 1, Str: "hello"},
			{Num: 100, Str: "world"},
		}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestCustomFooMUS_ValidateLength(t *testing.T) {
	var (
		ser      = CustomFooMUS
		testCase = Foo{Num: 1, Str: string(make([]byte, 101))}
		wantErr  = errors.New("string too long")
	)
	test.TestValidation(testCase, ser, wantErr, t)
}
